### ISSUE TITLE
Inquiry: Will this library be updated to Angular V14

### ISSUE THREAD

**Issue by dfulgham** [abarghoud/ngx-reactive-form-class-validator#21]
With the addition of typed forms in Angular 14, will this library be updated to support this version?

**Comment by abarghoud** [comment]
Hello @dfulgham,
Sure, will let you know once it is done.

**Comment by abarghoud** [comment]
@dfulgham Besides the addition of untyped form classes, is there any things you might find necessary to adapt ?

**Comment by abarghoud** [comment]
@dfulgham Please update to v1.4.0 and let me know if something is not OK with it

**Comment by yash-303** [comment]
Currently I'm using angular v14.1.0 So give me type error in ClassValidatorFormControl.

Now : export class ClassValidatorFormControl<T = any> extends **FormControl<T> **

Solved: export class ClassValidatorFormControl<T = any> extends FormControl<T | any>;

There is formcontrol type error so please mearge that.
