### ISSUE TITLE
Angular 17 support

### ISSUE THREAD

**Issue by SvenvandenBerg** [abarghoud/ngx-reactive-form-class-validator#31]
I would like to request an update for this package to Angular 17.

**Comment by abarghoud** [comment]
Hi @SvenvandenBerg, I will work on it this weekend.

**Comment by abarghoud** [comment]
@SvenvandenBerg, just published [v1.7.0](https://www.npmjs.com/package/ngx-reactive-form-class-validator/v/1.7.0), Angular 17 compatible
