### ISSUE TITLE
Peer Dependencies Angular 18

### ISSUE THREAD

**Issue by efuturetoday** [abarghoud/ngx-reactive-form-class-validator#37]
Hi,

Thank you for your work. As I upgraded my projects to Angular 18, I experienced some issues with this package and its peer dependencies. I was very happy to see that you released version 1.8.0 to support Angular 18. However, I noticed that the npm package does not match the GitHub tag.

Please take a look here: [npm package](https://www.npmjs.com/package/ngx-reactive-form-class-validator/v/1.8.0?activeTab=code). The `package.json` still lists Angular 17 as a peer dependency.

Could you please push the correct tag?

Thank you!

**Comment by abarghoud** [comment]
Hi @efuturetoday,

Thank you for pointing out this issue, I fixed it and published a new version [v1.8.1](https://www.npmjs.com/package/ngx-reactive-form-class-validator/v/1.8.1).
